
name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.23
    - name: Checkout Repo
      uses: actions/checkout@v2
    - name: Tests
      run: make test
    - name: Coverage Report
      run: make mode=headless coverage